### ISSUE TITLE
Jingles

### ISSUE THREAD

**Issue by Richard399** [killfill/jingles#3]
Hi,

I have created a 4 playlists called 'Jingles' i.e. 'Jingles - M', 'Jingles - A'.

In the 'Music Files' section, I then created a 'Directory' called 'Jingles' in which I have added my jingles files.

With each file, I have added it to say 'Jingles - M' playlist so that it plays that particular file after each song. The Play List 'Jingles - M' has been set as a 'Jingle' using the 'Hide Metadata from Listeners ("Jingle Mode")

However, I think I have a setting wrong as the jingle is not playing at the appropriate time i .e after each song?

Would appreciate some guidance on this as I have been trying for a while now using various settings in trying to get this to work i .e after each song without success.

Hope this made sense :-)

In advance, many thanks

**Comment by Licenser** [comment]
Hi Richard I’m sorry about your issues but I’m fairly certain you got the wrong repository. This has absolutely nothing to do with music. I still hope you can solve your problem!

**Comment by Richard399** [comment]
Hi

Thank you for that, my apologies :-)
